// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlwfi-hhviP5vyxWLqdlZ06UsN9cjmeg',
    appId: '1:555118360687:web:72da864841b1e0ca2cf59a',
    messagingSenderId: '555118360687',
    projectId: 'final-project-2025-ejseo',
    authDomain: 'final-project-2025-ejseo.firebaseapp.com',
    storageBucket: 'final-project-2025-ejseo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm1xyicjWTWOiMdKq1GrKBIszyOWdLGtU',
    appId: '1:555118360687:android:5c8cc281d77d24572cf59a',
    messagingSenderId: '555118360687',
    projectId: 'final-project-2025-ejseo',
    storageBucket: 'final-project-2025-ejseo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Fo-x9QcZGbd1OHwgSEF6PgcCsByrMT0',
    appId: '1:555118360687:ios:fad4cccfc9c201dc2cf59a',
    messagingSenderId: '555118360687',
    projectId: 'final-project-2025-ejseo',
    storageBucket: 'final-project-2025-ejseo.firebasestorage.app',
    iosBundleId: 'com.example.finalProject2025',
  );

}